package com.corona.backend.infra.goodbye_corona.json

data class Infection(
    val resultCode: String,
    val resultMessage: String,
    val TotalCase: String,
    val TotalRecovered: String,
    val TotalDeath: String,
    val NowCase: String,
    val city1n: String,
    val city2n: String,
    val city3n: String,
    val city4n: String,
    val city5n: String,
    val city1p: String,
    val city2p: String,
    val city3p: String,
    val city4p: String,
    val city5p: String,
    val recoveredPercentage: String,
    val deathPercentage: String,
    val checkingCounter: String,
    val checkingPercentage: String,
    val caseCount: String,
    val casePercentage: String,
    val notcaseCount: String,
    val notcasePercentage: String,
    val TotalChecking: String,
    val TodayRecovered: String,
    val TodayDeath: String,
    val TotalCaseBefore: String,
    val source: String,
    val updateTime: String,
)